'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SBMemberSecuritySvc
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="LoyaltyPlatformWS", ConfigurationName:="SBMemberSecuritySvc.MemberSecuritySoap")>  _
    Public Interface MemberSecuritySoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="LoyaltyPlatformWS/ValidatePassword", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ValidatePassword(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberPassword As String) As SBMemberSecuritySvc.ValidatePasswordReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="LoyaltyPlatformWS/ValidatePassword", ReplyAction:="*")>  _
        Function ValidatePasswordAsync(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberPassword As String) As System.Threading.Tasks.Task(Of SBMemberSecuritySvc.ValidatePasswordReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="LoyaltyPlatformWS/SetPassword", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SetPassword(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberNewPassword As String) As SBMemberSecuritySvc.SetPasswordReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="LoyaltyPlatformWS/SetPassword", ReplyAction:="*")>  _
        Function SetPasswordAsync(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberNewPassword As String) As System.Threading.Tasks.Task(Of SBMemberSecuritySvc.SetPasswordReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="LoyaltyPlatformWS/ChangePassword", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ChangePassword(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberCurrentPassword As String, ByVal MemberNewPassword As String) As SBMemberSecuritySvc.ChangePasswordReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="LoyaltyPlatformWS/ChangePassword", ReplyAction:="*")>  _
        Function ChangePasswordAsync(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberCurrentPassword As String, ByVal MemberNewPassword As String) As System.Threading.Tasks.Task(Of SBMemberSecuritySvc.ChangePasswordReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="LoyaltyPlatformWS/ValidatePIN", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ValidatePIN(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberPIN As String) As SBMemberSecuritySvc.ValidatePINReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="LoyaltyPlatformWS/ValidatePIN", ReplyAction:="*")>  _
        Function ValidatePINAsync(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberPIN As String) As System.Threading.Tasks.Task(Of SBMemberSecuritySvc.ValidatePINReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="LoyaltyPlatformWS/SetPIN", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SetPIN(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberNewPIN As String) As SBMemberSecuritySvc.SetPINReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="LoyaltyPlatformWS/SetPIN", ReplyAction:="*")>  _
        Function SetPINAsync(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberNewPIN As String) As System.Threading.Tasks.Task(Of SBMemberSecuritySvc.SetPINReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="LoyaltyPlatformWS/ChangePIN", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ChangePIN(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberCurrentPIN As String, ByVal MemberNewPIN As String) As SBMemberSecuritySvc.ChangePINReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="LoyaltyPlatformWS/ChangePIN", ReplyAction:="*")>  _
        Function ChangePINAsync(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberCurrentPIN As String, ByVal MemberNewPIN As String) As System.Threading.Tasks.Task(Of SBMemberSecuritySvc.ChangePINReturn)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="LoyaltyPlatformWS")>  _
    Partial Public Class ValidatePasswordReturn
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private returnCodeField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ReturnCode() As Integer
            Get
                Return Me.returnCodeField
            End Get
            Set
                Me.returnCodeField = value
                Me.RaisePropertyChanged("ReturnCode")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="LoyaltyPlatformWS")>  _
    Partial Public Class ChangePINReturn
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private returnCodeField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ReturnCode() As Integer
            Get
                Return Me.returnCodeField
            End Get
            Set
                Me.returnCodeField = value
                Me.RaisePropertyChanged("ReturnCode")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="LoyaltyPlatformWS")>  _
    Partial Public Class SetPINReturn
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private returnCodeField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ReturnCode() As Integer
            Get
                Return Me.returnCodeField
            End Get
            Set
                Me.returnCodeField = value
                Me.RaisePropertyChanged("ReturnCode")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="LoyaltyPlatformWS")>  _
    Partial Public Class ValidatePINReturn
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private returnCodeField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ReturnCode() As Integer
            Get
                Return Me.returnCodeField
            End Get
            Set
                Me.returnCodeField = value
                Me.RaisePropertyChanged("ReturnCode")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="LoyaltyPlatformWS")>  _
    Partial Public Class ChangePasswordReturn
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private returnCodeField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ReturnCode() As Integer
            Get
                Return Me.returnCodeField
            End Get
            Set
                Me.returnCodeField = value
                Me.RaisePropertyChanged("ReturnCode")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="LoyaltyPlatformWS")>  _
    Partial Public Class SetPasswordReturn
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private returnCodeField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ReturnCode() As Integer
            Get
                Return Me.returnCodeField
            End Get
            Set
                Me.returnCodeField = value
                Me.RaisePropertyChanged("ReturnCode")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface MemberSecuritySoapChannel
        Inherits SBMemberSecuritySvc.MemberSecuritySoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MemberSecuritySoapClient
        Inherits System.ServiceModel.ClientBase(Of SBMemberSecuritySvc.MemberSecuritySoap)
        Implements SBMemberSecuritySvc.MemberSecuritySoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ValidatePassword(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberPassword As String) As SBMemberSecuritySvc.ValidatePasswordReturn Implements SBMemberSecuritySvc.MemberSecuritySoap.ValidatePassword
            Return MyBase.Channel.ValidatePassword(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberPassword)
        End Function
        
        Public Function ValidatePasswordAsync(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberPassword As String) As System.Threading.Tasks.Task(Of SBMemberSecuritySvc.ValidatePasswordReturn) Implements SBMemberSecuritySvc.MemberSecuritySoap.ValidatePasswordAsync
            Return MyBase.Channel.ValidatePasswordAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberPassword)
        End Function
        
        Public Function SetPassword(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberNewPassword As String) As SBMemberSecuritySvc.SetPasswordReturn Implements SBMemberSecuritySvc.MemberSecuritySoap.SetPassword
            Return MyBase.Channel.SetPassword(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberNewPassword)
        End Function
        
        Public Function SetPasswordAsync(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberNewPassword As String) As System.Threading.Tasks.Task(Of SBMemberSecuritySvc.SetPasswordReturn) Implements SBMemberSecuritySvc.MemberSecuritySoap.SetPasswordAsync
            Return MyBase.Channel.SetPasswordAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberNewPassword)
        End Function
        
        Public Function ChangePassword(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberCurrentPassword As String, ByVal MemberNewPassword As String) As SBMemberSecuritySvc.ChangePasswordReturn Implements SBMemberSecuritySvc.MemberSecuritySoap.ChangePassword
            Return MyBase.Channel.ChangePassword(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberCurrentPassword, MemberNewPassword)
        End Function
        
        Public Function ChangePasswordAsync(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberCurrentPassword As String, ByVal MemberNewPassword As String) As System.Threading.Tasks.Task(Of SBMemberSecuritySvc.ChangePasswordReturn) Implements SBMemberSecuritySvc.MemberSecuritySoap.ChangePasswordAsync
            Return MyBase.Channel.ChangePasswordAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberCurrentPassword, MemberNewPassword)
        End Function
        
        Public Function ValidatePIN(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberPIN As String) As SBMemberSecuritySvc.ValidatePINReturn Implements SBMemberSecuritySvc.MemberSecuritySoap.ValidatePIN
            Return MyBase.Channel.ValidatePIN(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberPIN)
        End Function
        
        Public Function ValidatePINAsync(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberPIN As String) As System.Threading.Tasks.Task(Of SBMemberSecuritySvc.ValidatePINReturn) Implements SBMemberSecuritySvc.MemberSecuritySoap.ValidatePINAsync
            Return MyBase.Channel.ValidatePINAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberPIN)
        End Function
        
        Public Function SetPIN(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberNewPIN As String) As SBMemberSecuritySvc.SetPINReturn Implements SBMemberSecuritySvc.MemberSecuritySoap.SetPIN
            Return MyBase.Channel.SetPIN(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberNewPIN)
        End Function
        
        Public Function SetPINAsync(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberNewPIN As String) As System.Threading.Tasks.Task(Of SBMemberSecuritySvc.SetPINReturn) Implements SBMemberSecuritySvc.MemberSecuritySoap.SetPINAsync
            Return MyBase.Channel.SetPINAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberNewPIN)
        End Function
        
        Public Function ChangePIN(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberCurrentPIN As String, ByVal MemberNewPIN As String) As SBMemberSecuritySvc.ChangePINReturn Implements SBMemberSecuritySvc.MemberSecuritySoap.ChangePIN
            Return MyBase.Channel.ChangePIN(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberCurrentPIN, MemberNewPIN)
        End Function
        
        Public Function ChangePINAsync(ByVal WSSecurityToken As String, ByVal MemberAccountId As String, ByVal SBInternalMemberId As Integer, ByVal MemberCurrentPIN As String, ByVal MemberNewPIN As String) As System.Threading.Tasks.Task(Of SBMemberSecuritySvc.ChangePINReturn) Implements SBMemberSecuritySvc.MemberSecuritySoap.ChangePINAsync
            Return MyBase.Channel.ChangePINAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberCurrentPIN, MemberNewPIN)
        End Function
    End Class
End Namespace
