//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_NET_Web_App.SBMemberSecuritySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="LoyaltyPlatformWS", ConfigurationName="SBMemberSecuritySvc.MemberSecuritySoap")]
    public interface MemberSecuritySoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="LoyaltyPlatformWS/ValidatePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CS_NET_Web_App.SBMemberSecuritySvc.ValidatePasswordReturn ValidatePassword(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="LoyaltyPlatformWS/ValidatePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<CS_NET_Web_App.SBMemberSecuritySvc.ValidatePasswordReturn> ValidatePasswordAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="LoyaltyPlatformWS/SetPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CS_NET_Web_App.SBMemberSecuritySvc.SetPasswordReturn SetPassword(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberNewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="LoyaltyPlatformWS/SetPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<CS_NET_Web_App.SBMemberSecuritySvc.SetPasswordReturn> SetPasswordAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberNewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="LoyaltyPlatformWS/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CS_NET_Web_App.SBMemberSecuritySvc.ChangePasswordReturn ChangePassword(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberCurrentPassword, string MemberNewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="LoyaltyPlatformWS/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<CS_NET_Web_App.SBMemberSecuritySvc.ChangePasswordReturn> ChangePasswordAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberCurrentPassword, string MemberNewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="LoyaltyPlatformWS/ValidatePIN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CS_NET_Web_App.SBMemberSecuritySvc.ValidatePINReturn ValidatePIN(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberPIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="LoyaltyPlatformWS/ValidatePIN", ReplyAction="*")]
        System.Threading.Tasks.Task<CS_NET_Web_App.SBMemberSecuritySvc.ValidatePINReturn> ValidatePINAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberPIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="LoyaltyPlatformWS/SetPIN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CS_NET_Web_App.SBMemberSecuritySvc.SetPINReturn SetPIN(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberNewPIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="LoyaltyPlatformWS/SetPIN", ReplyAction="*")]
        System.Threading.Tasks.Task<CS_NET_Web_App.SBMemberSecuritySvc.SetPINReturn> SetPINAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberNewPIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="LoyaltyPlatformWS/ChangePIN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CS_NET_Web_App.SBMemberSecuritySvc.ChangePINReturn ChangePIN(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberCurrentPIN, string MemberNewPIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="LoyaltyPlatformWS/ChangePIN", ReplyAction="*")]
        System.Threading.Tasks.Task<CS_NET_Web_App.SBMemberSecuritySvc.ChangePINReturn> ChangePINAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberCurrentPIN, string MemberNewPIN);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class ValidatePasswordReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("ReturnCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class ChangePINReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("ReturnCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class SetPINReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("ReturnCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class ValidatePINReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("ReturnCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class ChangePasswordReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("ReturnCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="LoyaltyPlatformWS")]
    public partial class SetPasswordReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("ReturnCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MemberSecuritySoapChannel : CS_NET_Web_App.SBMemberSecuritySvc.MemberSecuritySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemberSecuritySoapClient : System.ServiceModel.ClientBase<CS_NET_Web_App.SBMemberSecuritySvc.MemberSecuritySoap>, CS_NET_Web_App.SBMemberSecuritySvc.MemberSecuritySoap {
        
        public MemberSecuritySoapClient() {
        }
        
        public MemberSecuritySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberSecuritySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberSecuritySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberSecuritySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CS_NET_Web_App.SBMemberSecuritySvc.ValidatePasswordReturn ValidatePassword(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberPassword) {
            return base.Channel.ValidatePassword(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberPassword);
        }
        
        public System.Threading.Tasks.Task<CS_NET_Web_App.SBMemberSecuritySvc.ValidatePasswordReturn> ValidatePasswordAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberPassword) {
            return base.Channel.ValidatePasswordAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberPassword);
        }
        
        public CS_NET_Web_App.SBMemberSecuritySvc.SetPasswordReturn SetPassword(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberNewPassword) {
            return base.Channel.SetPassword(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberNewPassword);
        }
        
        public System.Threading.Tasks.Task<CS_NET_Web_App.SBMemberSecuritySvc.SetPasswordReturn> SetPasswordAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberNewPassword) {
            return base.Channel.SetPasswordAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberNewPassword);
        }
        
        public CS_NET_Web_App.SBMemberSecuritySvc.ChangePasswordReturn ChangePassword(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberCurrentPassword, string MemberNewPassword) {
            return base.Channel.ChangePassword(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberCurrentPassword, MemberNewPassword);
        }
        
        public System.Threading.Tasks.Task<CS_NET_Web_App.SBMemberSecuritySvc.ChangePasswordReturn> ChangePasswordAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberCurrentPassword, string MemberNewPassword) {
            return base.Channel.ChangePasswordAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberCurrentPassword, MemberNewPassword);
        }
        
        public CS_NET_Web_App.SBMemberSecuritySvc.ValidatePINReturn ValidatePIN(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberPIN) {
            return base.Channel.ValidatePIN(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberPIN);
        }
        
        public System.Threading.Tasks.Task<CS_NET_Web_App.SBMemberSecuritySvc.ValidatePINReturn> ValidatePINAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberPIN) {
            return base.Channel.ValidatePINAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberPIN);
        }
        
        public CS_NET_Web_App.SBMemberSecuritySvc.SetPINReturn SetPIN(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberNewPIN) {
            return base.Channel.SetPIN(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberNewPIN);
        }
        
        public System.Threading.Tasks.Task<CS_NET_Web_App.SBMemberSecuritySvc.SetPINReturn> SetPINAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberNewPIN) {
            return base.Channel.SetPINAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberNewPIN);
        }
        
        public CS_NET_Web_App.SBMemberSecuritySvc.ChangePINReturn ChangePIN(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberCurrentPIN, string MemberNewPIN) {
            return base.Channel.ChangePIN(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberCurrentPIN, MemberNewPIN);
        }
        
        public System.Threading.Tasks.Task<CS_NET_Web_App.SBMemberSecuritySvc.ChangePINReturn> ChangePINAsync(string WSSecurityToken, string MemberAccountId, int SBInternalMemberId, string MemberCurrentPIN, string MemberNewPIN) {
            return base.Channel.ChangePINAsync(WSSecurityToken, MemberAccountId, SBInternalMemberId, MemberCurrentPIN, MemberNewPIN);
        }
    }
}
